// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protocol_contract.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Protocol service

type ProtocolService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Protocol_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Protocol_PingPongService, error)
}

type protocolService struct {
	c    client.Client
	name string
}

func NewProtocolService(name string, c client.Client) ProtocolService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "protocol"
	}
	return &protocolService{
		c:    c,
		name: name,
	}
}

func (c *protocolService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Protocol.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protocolService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Protocol_StreamService, error) {
	req := c.c.NewRequest(c.name, "Protocol.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &protocolServiceStream{stream}, nil
}

type Protocol_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type protocolServiceStream struct {
	stream client.Stream
}

func (x *protocolServiceStream) Close() error {
	return x.stream.Close()
}

func (x *protocolServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *protocolServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *protocolServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *protocolService) PingPong(ctx context.Context, opts ...client.CallOption) (Protocol_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Protocol.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &protocolServicePingPong{stream}, nil
}

type Protocol_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type protocolServicePingPong struct {
	stream client.Stream
}

func (x *protocolServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *protocolServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *protocolServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *protocolServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *protocolServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Protocol service

type ProtocolHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Protocol_StreamStream) error
	PingPong(context.Context, Protocol_PingPongStream) error
}

func RegisterProtocolHandler(s server.Server, hdlr ProtocolHandler, opts ...server.HandlerOption) error {
	type protocol interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Protocol struct {
		protocol
	}
	h := &protocolHandler{hdlr}
	return s.Handle(s.NewHandler(&Protocol{h}, opts...))
}

type protocolHandler struct {
	ProtocolHandler
}

func (h *protocolHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ProtocolHandler.Call(ctx, in, out)
}

func (h *protocolHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ProtocolHandler.Stream(ctx, m, &protocolStreamStream{stream})
}

type Protocol_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type protocolStreamStream struct {
	stream server.Stream
}

func (x *protocolStreamStream) Close() error {
	return x.stream.Close()
}

func (x *protocolStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *protocolStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *protocolStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *protocolHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ProtocolHandler.PingPong(ctx, &protocolPingPongStream{stream})
}

type Protocol_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type protocolPingPongStream struct {
	stream server.Stream
}

func (x *protocolPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *protocolPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *protocolPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *protocolPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *protocolPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
